version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=voting_system
      - DB_SYNC=true
      - JWT_SECRET=jwtSecretKey123ForVotingSystem
      - JWT_EXPIRATION=3600
      - JWT_REFRESH_EXPIRATION=86400
      - NODE_ENV=development
      - ETH_RPC_URL=http://ganache:8545
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
      - ganache
    networks:
      - app-network
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  # Database service
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=voting_system
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  # Local Ethereum blockchain for development
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    command:
      - "--deterministic"
      - "--db=/data"
      - "--mnemonic=test test test test test test test test test test test junk"
      - "--networkId=5777"
      - "--host=0.0.0.0"
    volumes:
      - ganache-data:/data
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  ganache-data: 